In [2]:
import pandas as pd
import numpy as np

In [3]:
data = pd.read_csv("./data/Ecommerce_Customers.csv")

In [4]:
data.drop(labels=["Email"], axis = 1, inplace=True)

In [5]:
data.drop(labels=["Address"], axis=1, inplace=True)

In [6]:
data.drop(labels=["Avatar"], axis=1, inplace=True)

In [7]:
data

Avg. Session Length  Time on App  Time on Website  Length of Membership  \
0              34.497268    12.655651        39.577668              4.082621   
1              31.926272    11.109461        37.268959              2.664034   
2              33.000915    11.330278        37.110597              4.104543   
3              34.305557    13.717514        36.721283              3.120179   
4              33.330673    12.795189        37.536653              4.446308   
..                   ...          ...              ...                   ...   
495            33.237660    13.566160        36.417985              3.746573   
496            34.702529    11.695736        37.190268              3.576526   
497            32.646777    11.499409        38.332576              4.958264   
498            33.322501    12.391423        36.840086              2.336485   
499            33.715981    12.418808        35.771016              2.735160   

     Yearly Amount Spent  
0             587.951054  
1             392.204933  
2             487.547505  
3             581.852344  
4             599.406092  
..                   ...  
495           573.847438  
496           529.049004  
497           551.620145  
498           456.469510  
499           497.778642  

[500 rows x 5 columns]

## Independent Features

In [8]:
X = data.drop(labels=["Yearly Amount Spent"], axis=1)
X

Avg. Session Length  Time on App  Time on Website  Length of Membership
0              34.497268    12.655651        39.577668              4.082621
1              31.926272    11.109461        37.268959              2.664034
2              33.000915    11.330278        37.110597              4.104543
3              34.305557    13.717514        36.721283              3.120179
4              33.330673    12.795189        37.536653              4.446308
..                   ...          ...              ...                   ...
495            33.237660    13.566160        36.417985              3.746573
496            34.702529    11.695736        37.190268              3.576526
497            32.646777    11.499409        38.332576              4.958264
498            33.322501    12.391423        36.840086              2.336485
499            33.715981    12.418808        35.771016              2.735160

[500 rows x 4 columns]

In [9]:
Y = data["Yearly Amount Spent"]
Y

0      587.951054
1      392.204933
2      487.547505
3      581.852344
4      599.406092
          ...    
495    573.847438
496    529.049004
497    551.620145
498    456.469510
499    497.778642
Name: Yearly Amount Spent, Length: 500, dtype: float64

## Seggregation of Categorical and Numerical Column, but we have Only Numerical Data

In [10]:
X.select_dtypes(include="object").columns
# No categorical Columns

Index([], dtype='object')

In [11]:
# Categorical Column
Categorical_columns = X.select_dtypes(include="object").columns
Categorical_columns

Index([], dtype='object')

In [12]:
# Numerical Column
Numerical_columns = X.select_dtypes(exclude="object").columns
Numerical_columns

Index(['Avg. Session Length', 'Time on App', 'Time on Website',
       'Length of Membership'],
      dtype='object')

In [13]:
X.select_dtypes(exclude="object")

Avg. Session Length  Time on App  Time on Website  Length of Membership
0              34.497268    12.655651        39.577668              4.082621
1              31.926272    11.109461        37.268959              2.664034
2              33.000915    11.330278        37.110597              4.104543
3              34.305557    13.717514        36.721283              3.120179
4              33.330673    12.795189        37.536653              4.446308
..                   ...          ...              ...                   ...
495            33.237660    13.566160        36.417985              3.746573
496            34.702529    11.695736        37.190268              3.576526
497            32.646777    11.499409        38.332576              4.958264
498            33.322501    12.391423        36.840086              2.336485
499            33.715981    12.418808        35.771016              2.735160

[500 rows x 4 columns]

## Scaling, Encoding and Data Transformation

In [29]:
from sklearn.impute import SimpleImputer ## HAndling Missing Values
from sklearn.preprocessing import StandardScaler # HAndling Feature Scaling
from sklearn.preprocessing import OrdinalEncoder # Ordinal Encoding
## pipelines
from sklearn.pipeline import Pipeline
from sklearn.compose import TransformedTargetRegressor
from sklearn.ensemble import RandomForestClassifier

In [16]:
num_pipeline = Pipeline(
    
    steps=[
        ('imputer',SimpleImputer()),   # imputer is the name given, u can remove it as well
        ('scaler', StandardScaler())  #Feature scaling
        
    ]
)

Preprocessor for numerical data

In [40]:
preprocessor_pipeline = Pipeline(steps=[
    ('preprocessor', num_pipeline),
    ('classifier', RandomForestClassifier())
])


## Splitting the Data into Train and Test

In [33]:
## Train test split
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,Y,test_size=0.30,random_state=30)

In [34]:
X_train

Avg. Session Length  Time on App  Time on Website  Length of Membership
12             29.532429    10.961298        37.420216              4.046423
136            32.686129    12.215252        36.594362              3.897116
368            34.385820    12.729720        36.232110              5.705941
367            32.990599    10.441235        35.938963              2.895075
406            32.865301    12.074830        35.569170              2.399080
..                   ...          ...              ...                   ...
140            31.066218    11.735095        36.599374              3.958892
301            33.026420    13.186813        38.066930              2.898300
429            33.292587    11.906508        38.422865              3.376687
421            31.574138    12.941556        36.725277              4.560396
293            33.794756    10.982806        34.810631              3.201802

[350 rows x 4 columns]

In [55]:
preprocessor_pipeline['preprocessor'].fit_transform(X_train)


array([[-3.42640671, -1.09520731,  0.37593714,  0.53573786],
       [-0.30305665,  0.1395892 , -0.44830155,  0.39291239],
       [ 1.38027709,  0.64619642, -0.80984495,  2.1232112 ],
       ...,
       [ 0.29756504, -0.16443856,  1.37662589, -0.10492274],
       [-1.40434643,  0.85479627, -0.31764245,  1.02739779],
       [ 0.79490096, -1.07402876, -2.22854319, -0.27221625]])

## Train data Fit Transform

In [42]:
X_train_transformed = preprocessor_pipeline['preprocessor'].fit_transform(X_train)


## Test data Transform

In [43]:
X_test_transformed = preprocessor_pipeline['preprocessor'].transform(X_test)

In [57]:
X_train

Avg. Session Length  Time on App  Time on Website  Length of Membership
12             29.532429    10.961298        37.420216              4.046423
136            32.686129    12.215252        36.594362              3.897116
368            34.385820    12.729720        36.232110              5.705941
367            32.990599    10.441235        35.938963              2.895075
406            32.865301    12.074830        35.569170              2.399080
..                   ...          ...              ...                   ...
140            31.066218    11.735095        36.599374              3.958892
301            33.026420    13.186813        38.066930              2.898300
429            33.292587    11.906508        38.422865              3.376687
421            31.574138    12.941556        36.725277              4.560396
293            33.794756    10.982806        34.810631              3.201802

[350 rows x 4 columns]

In [60]:
X_train_transformed.shape

(350, 4)

In [61]:
X_train_transformed

array([[-3.42640671, -1.09520731,  0.37593714,  0.53573786],
       [-0.30305665,  0.1395892 , -0.44830155,  0.39291239],
       [ 1.38027709,  0.64619642, -0.80984495,  2.1232112 ],
       ...,
       [ 0.29756504, -0.16443856,  1.37662589, -0.10492274],
       [-1.40434643,  0.85479627, -0.31764245,  1.02739779],
       [ 0.79490096, -1.07402876, -2.22854319, -0.27221625]])

In [59]:
X_test_transformed

array([[ 5.06039199e-01,  7.92195474e-01,  3.96702211e-01,
        -1.84355410e+00],
       [-1.25912569e+00, -3.16247872e-01,  1.52707101e+00,
         1.47081246e+00],
       [ 4.41409524e-01,  5.13949037e-01, -7.79981469e-01,
        -4.94298978e-01],
       [ 5.54183254e-01,  8.37877527e-02, -4.67491855e-01,
         1.88217872e+00],
       [-1.44647064e+00,  1.28512687e+00,  1.68715836e+00,
        -1.18733921e+00],
       [ 4.64412731e-01, -1.18593430e+00, -1.41831995e+00,
        -1.43091051e-02],
       [ 1.51615605e+00, -6.57525766e-01, -6.63969596e-01,
         5.30784462e-01],
       [-7.23101143e-01, -4.21981077e-01, -1.66321744e-02,
        -2.38801613e-01],
       [ 7.95266393e-01, -4.45587864e-01,  1.37323577e+00,
         1.02673106e+00],
       [-4.88986119e-01,  1.31683139e+00, -1.05099323e+00,
        -2.88653347e-01],
       [ 5.02492507e-01, -1.24967814e-01, -5.56126867e-01,
         4.31890246e-01],
       [ 9.13012418e-01,  1.90057612e-01, -4.67594454e-01,
      

# Model Training

In [62]:
## Model Training

from sklearn.linear_model import LinearRegression,Lasso,Ridge,ElasticNet
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error

## Evaluating the Model

In [63]:
import numpy as np
def evaluate_model(true, predicted):
    mae = mean_absolute_error(true, predicted)
    mse = mean_squared_error(true, predicted)
    rmse = np.sqrt(mean_squared_error(true, predicted))
    r2_square = r2_score(true, predicted)
    return mae, rmse, r2_square

In [64]:
## Train multiple models

models={
    'LinearRegression':LinearRegression(),
    'Lasso':Lasso(),
    'Ridge':Ridge(),
    'Elasticnet':ElasticNet()
}

In [65]:
trained_model_list=[]
model_list=[]
r2_list=[]

In [66]:
list(models)

['LinearRegression', 'Lasso', 'Ridge', 'Elasticnet']

In [67]:
for i in range(len(list(models))):
    model=list(models.values())[i]
    print(model)

LinearRegression()
Lasso()
Ridge()
ElasticNet()


In [69]:
models.keys()

dict_keys(['LinearRegression', 'Lasso', 'Ridge', 'Elasticnet'])

In [70]:
for i in range(len(list(models))):
    model=list(models.values())[i]
    model.fit(X_train,y_train)

    #Make Predictions
    y_pred=model.predict(X_test)

    #this is a validation(test) score
    mae, rmse, r2_square=evaluate_model(y_test,y_pred)

    print(list(models.keys())[i])
    model_list.append(list(models.keys())[i])

    print('Model Training Performance')
    print("RMSE:",rmse)
    print("MAE:",mae)
    print("R2 score",r2_square*100)

    r2_list.append(r2_square)
    
    print('='*35)
    print('\n')

LinearRegression
Model Training Performance
RMSE: 8.907519215617684
MAE: 7.1331791215881575
R2 score 98.25414050563545


Lasso
Model Training Performance
RMSE: 9.200191677448752
MAE: 7.356015676730466
R2 score 98.13752906361991


Ridge
Model Training Performance
RMSE: 8.9348530024718
MAE: 7.156261735619102
R2 score 98.24340930902295


Elasticnet
Model Training Performance
RMSE: 23.56281996505386
MAE: 18.64867111558315
R2 score 87.78340200008996




In [71]:
trained_model_list

[]

In [72]:
model_list

['LinearRegression', 'Lasso', 'Ridge', 'Elasticnet']

In [73]:
r2_list

[0.9825414050563545,
 0.9813752906361991,
 0.9824340930902294,
 0.8778340200008996]

In [74]:
for i in range(len(list(models))):
    model=list(models.values())[i]
    model.fit(X_train_transformed,y_train)

    #Make Predictions
    y_pred=model.predict(X_test_transformed)

    #this is a validation(test) score
    mae, rmse, r2_square=evaluate_model(y_test,y_pred)

    print(list(models.keys())[i])
    model_list.append(list(models.keys())[i])

    print('Model Training Performance')
    print("RMSE:",rmse)
    print("MAE:",mae)
    print("R2 score",r2_square*100)

    r2_list.append(r2_square)
    
    print('='*35)
    print('\n')

LinearRegression
Model Training Performance
RMSE: 8.907519215617727
MAE: 7.133179121588185
R2 score 98.25414050563543


Lasso
Model Training Performance
RMSE: 9.208251330781348
MAE: 7.363444089196485
R2 score 98.13426446966149


Ridge
Model Training Performance
RMSE: 8.936137582648207
MAE: 7.157441481173484
R2 score 98.24290417619349


Elasticnet
Model Training Performance
RMSE: 24.40877890638628
MAE: 19.319793904087746
R2 score 86.890447702397




In [75]:
r2_list

[0.9825414050563545,
 0.9813752906361991,
 0.9824340930902294,
 0.8778340200008996,
 0.9825414050563543,
 0.9813426446966149,
 0.9824290417619349,
 0.86890447702397]